version: '3'

services:
  mysql:
    container_name: djdn_warning
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: djdn
      MYSQL_PASSWORD: djdn
      MYSQL_DATABASE: djdn_warning
    ports:
      - "3307:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"