spring:

  jpa:
    properties:
      hibernate:
        format_sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/djdn_warning
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: djdn
    password: djdn

debug: true